
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COLON COMMA DEF EQUAL IDENTIFIER LPAREN RPARENfunction_declaration : DEF IDENTIFIER LPAREN parameter_list RPAREN COLONparameter_list : parameters\n                      | emptyparameters : parameter\n                  | parameter COMMA parametersparameter : IDENTIFIER\n                 | IDENTIFIER EQUAL IDENTIFIERempty :'
    
_lr_action_items = {'DEF':([0,],[2,]),'$end':([1,14,],[0,-1,]),'IDENTIFIER':([2,4,10,12,],[3,5,13,5,]),'LPAREN':([3,],[4,]),'RPAREN':([4,5,6,7,8,9,13,15,],[-8,-6,11,-2,-3,-4,-7,-5,]),'COMMA':([5,9,13,],[-6,12,-7,]),'EQUAL':([5,],[10,]),'COLON':([11,],[14,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'function_declaration':([0,],[1,]),'parameter_list':([4,],[6,]),'parameters':([4,12,],[7,15,]),'empty':([4,],[8,]),'parameter':([4,12,],[9,9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> function_declaration","S'",1,None,None,None),
  ('function_declaration -> DEF IDENTIFIER LPAREN parameter_list RPAREN COLON','function_declaration',6,'p_function_declaration','parser.py',6),
  ('parameter_list -> parameters','parameter_list',1,'p_parameter_list','parser.py',10),
  ('parameter_list -> empty','parameter_list',1,'p_parameter_list','parser.py',11),
  ('parameters -> parameter','parameters',1,'p_parameters','parser.py',15),
  ('parameters -> parameter COMMA parameters','parameters',3,'p_parameters','parser.py',16),
  ('parameter -> IDENTIFIER','parameter',1,'p_parameter','parser.py',20),
  ('parameter -> IDENTIFIER EQUAL IDENTIFIER','parameter',3,'p_parameter','parser.py',21),
  ('empty -> <empty>','empty',0,'p_empty','parser.py',25),
]
